apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
        - name: demo-web
          image: mydockerhubuser/demo-app:latest
          ports:
            - containerPort: 8080
